name: Build and Test

on:
  push:
    branches:
      - dev # Spécifiez la branche ici

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Build
        run: echo "Building the project..."

      - name: Run Tests
        run: echo "Running tests..."
