name: Validation

on:
    pull_request:
        branches:
            - main

jobs:
    validate:
        name: Validate and Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Run validation
              run: npm run validate

            - name: Build
              run: npm run build
